language: python
env:
  - PYTHON_VERSION=3.8 IPYTHON_KERNEL=python3
before_install:
    - wget -q http://repo.continuum.io/miniconda/Miniconda-3.6.0-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p /home/travis/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes --quiet conda
install:
    - conda create -n testenv --yes pip python=$PYTHON_VERSION
    - source activate testenv
    - pip install -q flake8 nbconvert[test]
    - pip install -r requirements.txt
script:
    - flake8 *.py submissions/*/*.py --exclude plot_topomap.py
    - python download_data.py
    - ramp-test --quick-test
    - ramp-test --submission lasso_lars --quick-test
    - jupyter nbconvert --execute meg_starting_kit.ipynb --ExecutePreprocessor.kernel_name=$IPYTHON_KERNEL
notifications:
  email: true
